### ISSUE TITLE
Add philss list of streams to the live coding list

### ISSUE THREAD

**Issue by pdgonzalez872** [adolfont/elixir_cop#4]
@adolfont thanks for putting this list together.

I think you should add the work done by @philss if he approves it.

I'll create an MR to add it, if @philss approves and you'd like to merge it, please do! Hope it helps.

And thanks for doing this type of work @philss! It helps our community so much, thank you!

**Comment by philss** [comment]
@pdgonzalez872 thank you for remembering me! :purple_heart: 

For sure I approve :+1:  But I think it's easier to add only the link of the repository where I keep the list of episodes. I have a bunch of episodes that I want to upload and update that list. I think with the link only it would be easier to keep up-to-date. WDYT?

**Comment by pdgonzalez872** [comment]
@philss makes sense, I don't really think this type of info gathering is scalable, but thought I'd at least try to keep up with @adolfont original idea of listing each video.

On one hand, I like how this page would have a boatload of videos, with their titles and a description. On the other (your point), if we have people producing content like you plan to then it becomes an issue. Haha, can you just stop producing content? That seems like possible solution too! /s

Just updated the PR with your suggestion. Thanks again!
